betterbib=bibliography_better.bib
TEXFILES := $(shell find . -name '*.tex')
SVGFILES := $(shell find . -name '*.svg')


.PHONY : revision.tex
revision.tex:
	echo "% Autogenerated, do not edit" > revision.tex
	echo "\\newcommand{\\revisiondate}{`git show -s --format=\"%ci\" HEAD`}" >> revision.tex
	echo "\\newcommand{\\revision}{`git log -1 --format=\"%h\"`}" >> revision.tex

.PHONY: ${TEXFILES}
${TEXFILES}: ; latexindent -w -t -s $@

.PHONY: lint
lint: ${TEXFILES}
	rm *.bak*
	echo Lint finished

$(betterbib): bibliography.bib
	latexindent -w -t -s bibliography.bib
	betterbib bibliography.bib bibliography_better.bib

.PHONY: ${SVGFILES}
${SVGFILES}: ; inkscape $@ --export-type=pdf

.PHONY: svg
svg: ${SVGFILES}
	echo SVG converted

pdf: $(betterbib) lint svg revision.tex
	latexmk --xelatex -latexoption="-shell-escape" thesis

publish: pdf
	scp thesis.pdf vps:/var/www/html/thesis.pdf

clean:
	rm *.aux
	rm *.bbl
	rm *.blg
	rm *.fdb_latexmk
	rm *.fls
	rm *.log
	rm *.toc
	rm *.xdv
	rm revision.tex
	rm bibliography_better.bib